### ISSUE TITLE
fading

### ISSUE THREAD

**Issue by pcout** [awbush/jquery-fastLiveFilter#1]
Is ite possible to fadeIn and fadeOut the items when showing and hiding them ?

**Comment by awbush** [comment]
There is no option for this because it is slow and distracting.  You can use one of the slower alternatives if this is important, e.g. http://kilianvalkhof.com/uploads/listfilter/.

**Comment by pcout** [comment]
But can´t var oldDisplay = len > 0 ? lis[0].style.display : "block";
be changed to have a fadeIn()  ?

Is it possible for me to alter the code a liitle bit ?

**Comment by awbush** [comment]
You're more than welcome to fork it, but the change isn't quite that simple (though it isn't too difficult): you'd just need to change all portions that reference `li.style.display` into something else, maybe `li.fadeIn()` or `$(li).fadeIn()` (not sure which, you'd have to test it)

**Comment by awbush** [comment]
This is probably the change you'd need:

```
=== modified file 'jquery.fastLiveFilter.js'
--- jquery.fastLiveFilter.js    2011-11-07 22:06:24 +0000
+++ jquery.fastLiveFilter.js    2011-11-08 18:18:55 +0000
@@ -32,12 +32,14 @@
            li = lis[i];
            if ((li.textContent || "").toLowerCase().indexOf(filter) >= 0) {
                if (li.style.display == "none") {
-                   li.style.display = oldDisplay;
+                   $(li).fadeIn();
                }
                numShown++;
            } else {
                if (li.style.display != "none") {
-                   li.style.display = "none";
+                   $(li).fadeOut();
                }
            }
        }
```

It might be faster to use jQuery's `.each()` instead of `$(li)` inside the loop.  For small data sets, it may not matter much.

**Comment by pcout** [comment]
Thank you.
This worked.

What did you mean with using each() instead of $(li) ?
Is it like this ? $li.each().fadeOut();

**Comment by awbush** [comment]
No, it'd be more like the examples in the [jQuery each() API](http://api.jquery.com/each/), but after glancing at it I don't think it'd be any faster.

**Comment by pcout** [comment]
ok. thank you.
Nice work.

**Comment by awbush** [comment]
No problem! Glad I could help.
