### ISSUE TITLE
Add option to highlight the keyword(s) in the string

### ISSUE THREAD

**Issue by CodeBrauer** [awbush/jquery-fastLiveFilter#10]
I have one request, that should be possible. I think it would be very useful for longer strings, when the filter would highlight or just bold or underline the keywords. 

``` javascript
.css('background-color', 'yellow');
```

^ This should it be, but i don't know where i should paste that...

Many thanks in advance for your help

ps.: awesome script !

**Comment by awbush** [comment]
Yeah, we should find a way to work this in as an optional feature so it doesn't slow down users who don't want to use it.

**Comment by marqsm** [comment]
One easy way to achieve this, is to use some separate highlight (like https://github.com/bartaz/sandbox.js/blob/master/jquery.highlight.js )  plugin, and use the filter callback. 

eg. 

``` javascript
$('#searchTerm').fastLiveFilter('#eventList', { 
        callback:function(total) {
        $('#myList').unhighlight();
        searchTerm = $("#searchTerm").val();
        if (searchTerm.length > 0) {
            $('#myList').highlight(searchTerm);
        }
    }
});
```

**Comment by CodeBrauer** [comment]
Thanks :+1:
