### ISSUE TITLE
clear text button

### ISSUE THREAD

**Issue by pcout** [awbush/jquery-fastLiveFilter#2]
maybe you could help me with one more thing.

I want to have a button that erases the text on the  #search_input text field and returns the list to its initial state (all visible), instead of deletinf the text inserted manually.

I tried an onclick function setting the text field val to nothing, like this: $('#search_input').val(''); and $('#search_input').attr('value', '');

It clears the text but it doesn´t returns the list visible.

Can you help me ?

**Comment by awbush** [comment]
Try this:

```
$('#search_input').val('').change();
```

The text input's onchange event is what updates the list, and it probably isn't getting called when you update the text input manually.  The above should do the trick.

**Comment by pcout** [comment]
perfect !
thank you !
